const scroll = new LocomotiveScroll({
  el: document.querySelector("[data-scroll-container]"),
  smooth: true,
});

gsap.from(".nlink", {
  stagger: 0.1,
  y: 20,
  duration: 1.5,
  ease: "power3.out",
  opacity: 0,
});

Shery.textAnimate(".heading h1", {
  style: 2,
  y: 20,
  delay: 0.1,
  duration: 1.5,
  ease: "cubic-bezier(0.23, 1, 0.320, 1)",
  multiplier: 0.1,
});

gsap.from(".animation-2", {
  stagger: 0.1,
  y: 50,
  duration: 1.5,
  ease: "Expo.out",
  opacity: 0,
});

// Shery.imageEffect(".ephem-image-wrapper img", {
//   style: 3,
//   config: {
//     uFrequencyX: { value: 12, range: [0, 100] },
//     uFrequencyY: { value: 12, range: [0, 100] },
//     uFrequencyZ: { value: 10, range: [0, 100] },
//     geoVertex: { range: [1, 64], value: 32 },
//     zindex: { value:-1, range: [-9999999, 9999999] },
//     aspect: { value: 0.75 },
//     ignoreShapeAspect: { value: true },
//     shapePosition: { value: { x: 0, y: 0 } },
//     shapeScale: { value: { x: 0.5, y: 0.5 } },
//     shapeEdgeSoftness: { value: 0, range: [0, 0.5] },
//     shapeRadius: { value: 0, range: [0, 2] },
//     currentScroll: { value: 0 },
//     scrollLerp: { value: 0.07 },
//     gooey: { value: false },
//     infiniteGooey: { value: false },
//     growSize: { value: 4, range: [1, 15] },
//     durationOut: { value: 1, range: [0.1, 5] },
//     durationIn: { value: 1.5, range: [0.1, 5] },
//     displaceAmount: { value: 0.5 },
//     masker: { value: true },
//     maskVal: { value: 1.21, range: [1, 5] },
//     scrollType: { value: 0 },
//     noEffectGooey: { value: true },
//     onMouse: { value: 1 },
//     noise_speed: { value: 0.2, range: [0, 10] },
//     metaball: { value: 0.2, range: [0, 2] },
//     discard_threshold: { value: 0.5, range: [0, 1] },
//     antialias_threshold: { value: 0.002, range: [0, 0.1] },
//     noise_height: { value: 0.5, range: [0, 2] },
//     noise_scale: { value: 10, range: [0, 100] },
//   },
// });

Shery.imageEffect(".image-effect img", {
  style: 5,
  config: {
    a: { value: 2, range: [0, 30] },
    b: { value: 0.75, range: [-1, 1] },
    zindex: { value: 1, range: [-9999999, 9999999] },
    aspect: { value: 0.6785714285714286 },
    ignoreShapeAspect: { value: false },
    shapePosition: { value: { x: 0, y: 0 } },
    shapeScale: { value: { x: 0.5, y: 0.5 } },
    shapeEdgeSoftness: { value: 0, range: [0, 0.5] },
    shapeRadius: { value: 0, range: [0, 2] },
    currentScroll: { value: 0 },
    scrollLerp: { value: 0.07 },
    gooey: { value: false },
    infiniteGooey: { value: false },
    growSize: { value: 4, range: [1, 15] },
    durationOut: { value: 1, range: [0.1, 5] },
    durationIn: { value: 1.5, range: [0.1, 5] },
    displaceAmount: { value: 0.5 },
    masker: { value: true },
    maskVal: { value: 1.34, range: [1, 5] },
    scrollType: { value: 0 },
    geoVertex: { range: [1, 64], value: 1 },
    noEffectGooey: { value: true },
    onMouse: { value: 1 },
    noise_speed: { value: 0.2, range: [0, 10] },
    metaball: { value: 0.2, range: [0, 2] },
    discard_threshold: { value: 0.5, range: [0, 1] },
    antialias_threshold: { value: 0.002, range: [0, 0.1] },
    noise_height: { value: 0.5, range: [0, 2] },
    noise_scale: { value: 10, range: [0, 100] },
  },
});

Shery.imageEffect(".product-image-wrapper", {
  style: 5,
  gooey: true,
  config: {
    a: { value: 0.92, range: [0, 30] },
    b: { value: -0.99, range: [-1, 1] },
    zindex: { value: 1, range: [-9999999, 9999999] },
    aspect: { value: 1.8246124417168135 },
    ignoreShapeAspect: { value: false },
    shapePosition: { value: { x: 0, y: 0 } },
    shapeScale: { value: { x: 0.5, y: 0.5 } },
    shapeEdgeSoftness: { value: 0, range: [0, 0.5] },
    shapeRadius: { value: 0, range: [0, 2] },
    currentScroll: { value: 0 },
    scrollLerp: { value: 0.07 },
    gooey: { value: true },
    infiniteGooey: { value: true },
    growSize: { value: 1, range: [1, 15] },
    durationOut: { value: 1, range: [0.1, 5] },
    durationIn: { value: 1.5, range: [0.1, 5] },
    displaceAmount: { value: 0.5 },
    masker: { value: true },
    maskVal: { value: 1.09, range: [1, 5] },
    scrollType: { value: 0 },
    geoVertex: { range: [1, 64], value: 1 },
    noEffectGooey: { value: true },
    onMouse: { value: 1 },
    noise_speed: { value: 0.2, range: [0, 10] },
    metaball: { value: 0.2, range: [0, 2], _gsap: { id: 32 } },
    discard_threshold: { value: 0.52, range: [0, 1] },
    antialias_threshold: { value: 0, range: [0, 0.1] },
    noise_height: { value: 0.29, range: [0, 2] },
    noise_scale: { value: 15.27, range: [0, 100] },
  },
});
